"use client"

import type React from "react"

import { useState } from "react"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Sparkles, Loader2 } from "lucide-react"
import { toast } from "@/hooks/use-toast"

interface PadSummaryModalProps {
  padId: string
  padName: string
  trigger: React.ReactNode
}

export function PadSummaryModal({ padId, padName, trigger }: PadSummaryModalProps) {
  const [isOpen, setIsOpen] = useState(false)
  const [loading, setLoading] = useState(false)
  const [summary, setSummary] = useState<string | null>(null)

  const handleGenerateSummary = async () => {
    if (summary) return // Don't regenerate if already exists

    try {
      setLoading(true)
      const response = await fetch("/api/ai/summarize-pad", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ padId }),
      })

      if (!response.ok) throw new Error("Failed to generate summary")

      const data = await response.json()
      setSummary(data.summary)
    } catch (error) {
      console.error("Error generating summary:", error)
      toast({
        title: "Error",
        description: "Failed to generate summary. Please try again.",
        variant: "destructive",
      })
    } finally {
      setLoading(false)
    }
  }

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <div
        onClick={() => {
          setIsOpen(true)
          if (!summary) handleGenerateSummary()
        }}
      >
        {trigger}
      </div>
      <DialogContent className="sm:max-w-[600px]">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-purple-500" />
            AI Summary: {padName}
          </DialogTitle>
          <DialogDescription>Smart summary of progress and content generated by AI.</DialogDescription>
        </DialogHeader>

        <div className="mt-4 min-h-[200px] max-h-[60vh] overflow-y-auto">
          {loading ? (
            <div className="flex flex-col items-center justify-center h-[200px] space-y-4">
              <Loader2 className="h-8 w-8 animate-spin text-primary" />
              <p className="text-sm text-muted-foreground">Analyzing pad content...</p>
            </div>
          ) : summary ? (
            <div className="prose prose-sm dark:prose-invert max-w-none">
              <div className="whitespace-pre-wrap">{summary}</div>
            </div>
          ) : (
            <div className="flex justify-center">
              <Button onClick={handleGenerateSummary}>Generate Summary</Button>
            </div>
          )}
        </div>

        <div className="flex justify-end gap-2 mt-4">
          {summary && (
            <Button variant="outline" size="sm" onClick={() => setSummary(null)}>
              Regenerate
            </Button>
          )}
          <Button variant="secondary" onClick={() => setIsOpen(false)}>
            Close
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  )
}
